/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface LocalSearch {
    'linkText': string;
    'mapUrl': string;
    'titleText': string;
  }
}

declare global {


  interface HTMLLocalSearchElement extends Components.LocalSearch, HTMLStencilElement {}
  var HTMLLocalSearchElement: {
    prototype: HTMLLocalSearchElement;
    new (): HTMLLocalSearchElement;
  };
  interface HTMLElementTagNameMap {
    'local-search': HTMLLocalSearchElement;
  }
}

declare namespace LocalJSX {
  interface LocalSearch {
    'linkText'?: string;
    'mapUrl'?: string;
    'titleText'?: string;
  }

  interface IntrinsicElements {
    'local-search': LocalSearch;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'local-search': LocalJSX.LocalSearch & JSXBase.HTMLAttributes<HTMLLocalSearchElement>;
    }
  }
}


